// The icons of the app: Lucide, one family, drawn a little heavier than usual so they sit well next to
// the round, bold type. The names stay the app's own, so a screen says what it means, not which icon.

import {
  ArrowLeft,
  ArrowRight,
  Building2,
  CalendarDays,
  Coins,
  ChartColumn,
  Check,
  Copy,
  Cpu,
  ExternalLink,
  Flame,
  GitBranch,
  Globe,
  KeyRound,
  Layers,
  Lightbulb,
  LogOut,
  type LucideIcon,
  Mail,
  Pause,
  Pencil,
  Plus,
  RefreshCw,
  Search,
  Send,
  Shield,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Target,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  Trophy,
  Crown,
  User,
  X,
  Zap,
} from 'lucide-react'

const ICONS = {
  today: Sun,
  projects: Layers,
  studio: Sparkles,
  quests: Target,
  companies: Building2,
  settings: SlidersHorizontal,
  branch: GitBranch,
  bolt: Zap,
  flame: Flame,
  plus: Plus,
  check: Check,
  copy: Copy,
  mail: Mail,
  refresh: RefreshCw,
  arrow: ArrowRight,
  back: ArrowLeft,
  external: ExternalLink,
  logout: LogOut,
  trash: Trash2,
  idea: Lightbulb,
  calendar: CalendarDays,
  chart: ChartColumn,
  user: User,
  key: KeyRound,
  shield: Shield,
  globe: Globe,
  up: ThumbsUp,
  down: ThumbsDown,
  send: Send,
  trophy: Trophy,
  crown: Crown,
  pause: Pause,
  search: Search,
  edit: Pencil,
  close: X,
  cpu: Cpu,
  coins: Coins,
} satisfies Record<string, LucideIcon>

export type IconName = keyof typeof ICONS

export function Icon({ name, size = 20, label }: { name: IconName; size?: number; label?: string }) {
  const Glyph = ICONS[name]
  return <Glyph size={size} strokeWidth={2.25} aria-hidden={label ? undefined : true} role={label ? 'img' : undefined} aria-label={label} focusable="false" />
}
